services:
  train:
    build:
      context: .
      dockerfile: docker/Dockerfile.train
    volumes:
      - ./output:/app/output
    restart: "no"

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.inference
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output
      - ./db:/app/db
    restart: unless-stopped
    depends_on:
      - train

  streamlit:
    build:
      context: .
      dockerfile: docker/Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api
