apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-pvc
  namespace: webapp-demo
  labels:
    app: output
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
